petergoldstein/dalli

lib/active_support/cache/dalli_store.rb, test/test_active_support.rb
Handle case when the entry is the boolean value 'false' that it should still be considered a hit.
- I did this as a quick inline fix, will still need to do verification.
=> Fix instrumentation of hits for falsey values

lib/dalli/client.rb, lib/dalli/ring.rb, lib/dalli/server.rb, lib/dalli/socket.rb, test/memcached_mock.rb, test/test_dalli.rb, test/test_network.rb, test/test_ring.rb, test/test_sasl.rb, test/test_server.rb
Please review and merge the connect_to_unix_socket branch. It adds support for connecting to memcached using a unix socket.
The user must use a full pathname (must begin with a slash character: '/') in place of the "host:port" pair argument to Dalli::Client.new method for connecting to a unix socket.
=> Connect to unix socket

History.md, README.md, lib/dalli/server.rb, lib/dalli/socket.rb, test/memcached_mock.rb, test/test_dalli.rb
I need to change the send and receive buffer sizes.
=> Add configuration support to override socket options.

lib/active_support/cache/dalli_store.rb, test/test_active_support.rb
Trying to set a counter value and using increment while inside a LocalCache block currently fails. LocalCache expects `read_entry`,  `write_entry` and  `delete_entry` to be dealing with `Entry` instances, but Dalli chooses to deal with unwrapped values. This means that writes for raw values would be subsequently read as a raw then `Entry` wrapped object.
This addresses the failure by making sure the `read_entry` interface unwraps potential Entry instances from LocalStore and performs a `to_s` on the unwrapped value if raw is requested. The implementation is similar to the [workaround in activesupport for MemCacheStore's raw support](https://github.com/rails/rails/blob/82e28492e7c581cdeea904464a18eb11118f4ac0/activesupport/lib/active_support/cache/mem_cache_store.rb#L175-L195).
The …
=> Make sure LocalCache respects Entry unwrapping and :raw option

lib/dalli/client.rb
Previous version of the comment has no close quote and might be clearer to read with an example rather than a format.
=> Comment revision

lib/dalli/client.rb, test/test_active_support.rb, test/test_dalli.rb
I experienced read_multi results coming back with nil keys.  Eventually I tracked it down to the namespace, which contained a base64-encoded component, but only when it contained the "+" character.
Normal
irb(main):009:0> Rails.cache.options[:namespace] = 'abc'
=> "abc"
irb(main):010:0> Rails.cache.write 'foo', 'bar'; puts Rails.cache.read 'foo'; Rails.cache.read_multi 'foo'
bar
=> {"foo"=>"bar"}
With special characters ("+")
irb(main):011:0> Rails.cache.options[:namespace] = 'a+c'
=> "a+c"
irb(main):012:0> Rails.cache.write 'foo', 'bar'; puts Rails.cache.read 'foo'; Rails.cache.read_multi 'foo'
bar
=> {nil=>"bar"}
Of course, other special regex characters will cause this, too, or possibly raise RegexpErrors (e.g., "[]").  Properly escaping the namespace when using a regexp to remove it …
=> Escape namespace when using a Regexp to replace it

dalli.gemspec
@mperham @petergoldstein
makes the gem lighter for those committing vendor/cache and install faster
leaving docs in case someone opens the gem up
=> stop shipping files that are not needed to run/understand the code

lib/dalli/client.rb
Fix Dalli::Client#get_multi_yielder so it doesn't timeout as long as
data is immediately available for reading.  We were seeing spurious
timeout errors such as:
memcache-host:11211 failed (count: 0) RuntimeError: External timeout
when doing large (100+ item) multi-get operations.  This fixes the problem.
=> fix timeout issue with Dalli::Client#get_multi_yielder

.travis.yml, Rakefile, dalli.gemspec
1. Call `gem install bundler` to ensure we have the latest bundler
2. Remove metric_fu dependency
3. Update Travis CI to use latest patches for Ruby 2.1 and 2.2
=> Fix some build issues with the new Travis environment

lib/dalli/client.rb, lib/dalli/server.rb, test/test_dalli.rb
If a ttl argument cannot be parsed to an integer with `to_i`, raise an error in the `Dalli::Client` as opposed to the `Dalli::Server`.  This ensures that a bad argument doesn't knock a server out of the ring.
=> Isolate errors in TTL arguments to Dalli::Client

lib/active_support/cache/dalli_store.rb
To be consistent with other events (e.g. `read`, `write`), namespaced keys should be passed to the subscribers of the following events:
- fetch_hit
- generate
- read_multi
- fetch_multi
=> Always pass namespaced key to the subscriber of instrumentation API

lib/dalli/client.rb, lib/dalli/server.rb, lib/dalli/socket.rb, lib/rack/session/dalli.rb
[`loop` is slower than `while true`](https://github.com/JuanitoFatas/fast-ruby/blob/master/code/general/loop-vs-while-true.rb). 
This appears to be a decently hot area of the code - running your included benchmark gets about 3-5% faster for me with this change. It's a pretty minor speedup, but a free one!
=> loop do -> while true

lib/dalli/client.rb
Yielding is always faster than using #call, because [with #call we have to create a Proc object](https://www.omniref.com/ruby/2.2.0/symbols/Proc/yield?#annotation=4087638&line=711).
This doesn't appear to be a super-hot area of the code, the impact on your included macrobenchmark cannot be assessed.
=> Yield over block.call

lib/dalli/ring.rb
This will perform better on a micro benchmark, but I don't this code gets called often enough for it to matter. Plus, I think Symbol#to_proc generally just sort of reads better :)
=> Ring symbol#to_proc

test/helper.rb
Explicitly include the Dalli cache adapter and ActiveSupport::Time to avoid intermittent failures in CI
=> Explicitly include the Dalli cache adapter and ActiveSupport::Time

lib/dalli/server.rb
There are a few additional response codes defined here - https://code.google.com/p/memcached/wiki/BinaryProtocolRevamped#Response_Status
This PR adds the missing response codes to the hash that is used to generate the error message.
=> Add additional response codes

lib/dalli/client.rb, test/test_dalli.rb
Looking for a variant of the #cas method that yields to the block whether or not the key already exists. This is to avoid having to do things like:
```ruby
result = dc.cas(key) { |oldvalue| newvalue }
result = dc.add(key, newvalue) if result.nil?
```
Thanks in advance.
=> Add #cas! method that yields whether or not the key exists

.travis.yml
Current .travis.yml does not include 'gemfiles/rails5.gemfile' to
gemfile, so tests for Rails 5 are not executed.
=> Execute tests for Rails 5

lib/dalli/server.rb, test/test_server.rb
Memcached allows expiration times to be specified as either relative to now or as a timestamp.
But since relative times only allows values less than 30 days, the code tried to handle larger valued by converting them to timestamps. This caused actual timestamps to be offset incorrectly.
Now it checks if the values looks like a timestamp (i.e. has a value like a future timestamp) before doing the conversion.
=> Handle timestamp TTLs

README.md, lib/dalli.rb, lib/dalli/server.rb, test/test_server.rb
When the payload to `set` is larger than `value_max_bytes`, it's currently almost quietly ignored (logs a warning), appearing to have succeeded.
This adds an `fatal_over_max` option (defaulting to false - the previous behaviour), that causes `guard_max_value` to raise a `Dalli::TooBig` exception in such cases, making the failure more explicit and noticeable.
(test failures seem unrelated)
Thoughts, anyone? :)
=> Add an option to raise an exception when trying to save too much data

lib/dalli/server.rb
This is a follow-up to #612, which doesn't currently behave as expected.
When actually using the `Server` instance as intended through the `request` interface, the `Dalli::ValueOverMaxSize` error was getting swallowed by the final `rescue => ex` branch since it wasn't added to the cases of whitelisted exceptions to re-raise.
Because of the way `test_server.rb` is written (using `send` to test private methods directly), there's unfortunately not really a good way to fix the tests to red/green this without serious refactoring.
=> Add ValueOverMaxSize to the whitelist of expected exceptions that get re-raised

lib/rack/session/dalli.rb, test/helper.rb, test/test_rack_session.rb
I tried do this with as small of a footprint as possible. Let me know if you'd like me to take a different approach, e.g. with argument checking, or eliminate the `with_lock` method entirely if it's a ConnectionPool. Thank you!
n.b. This addresses #562!
=> Modify Rack::Session::Dalli to be compatible with ConnectionPool

History.md, README.md, lib/active_support/cache/dalli_store.rb, test/test_active_support.rb
Previously, one could use raise_errors to either handle execptions
in client code or have them handled by dalli. In the later case,
logging was the only way to be notified of an exception. This
commit adds the ability to be notified via active support
instrumentation via a cache_error.active_support event.
I've added this code because I want to know when errors are
occuring to trigger external monitoring and I still want
dalli to fail without raising errors so that cached values
are still generated.
=> ActiveSupport instrument DalliStore errors

lib/dalli/socket.rb
Hello,
I had a trouble that my web application processes stil holds established TCP connections with remote Memcached servers after one `Dalli::Server` downs and `RingError` occurs.
I tried some times and found that when `Dalli::Server::KSocket#kgio_wait_writable` fails with `Timeout::Error`, the created sockets are left and survives after the error.
This patch worked well in my environment.
Though I tried only for TCP socket, I think this patch is applicable for UNIX socket, too.
Thanks,
=> Close kgio socket after IO.select timeouts

README.md, lib/dalli/server.rb
Update `down_retry_delay` for #621
I ran into this myself recently. I saw the existing issue and figured I’d throw together a quick pull request since nobody had done anything with this since it was raised back in May of last year.
=> Update down_retry_delay default

.travis.yml
* allow_failures is because it's good to know new version Ruby's issue
as faster before the release.
* fast_finish is to get the Travis result as faster
without waiting the result of the "allow_failures" items.
See https://blog.travis-ci.com/2013-11-27-fast-finishing-builds/
I want to add `ruby-head` as allow_failures in `.travis.yml`.
I think this is useful.
Because we can prepare before next version Ruby 2.5 release.
Though it might not be useful until the actual preview release.
We can support the next version as faster.
We can see this kind of logic in `rails`, `rspec` and `cucumber` and etc.
I think that is the reason why `rails` and `rspec` can support new version Ruby as faster.
https://github.com/rails/rails/blob/master/.travis.yml …
=> Add Ruby 2.4 to Travis and add ruby-head to Travis as allow_failures.

lib/active_support/cache/dalli_store.rb, test/test_active_support.rb
Triggering the equality method on the result from the fetch can
cause the state of the result object to change, for example if it has
a custom `==` instance method. By reversing the operands we end up
achieving a hit/miss determination but will call `#==` on `nil` or
on `Dalli::Server::NOT_FOUND` if `cache_nils` is `true`. Either way
we won't modify the returned object from the cache before sending it
back to the caller.
=> Not found checks no longer trigger the result's equality method

lib/rack/session/dalli.rb
There's no need to override the generate_sid method and call the super method via an alias because the get_session and destroy_session methods call generate_sid_with directly. This fixes the issue with the Rails subclass of Rack::Session::Dalli which overrides the generate_sid method for compatibility reasons.
=> Don't override generate_sid

lib/active_support/cache/dalli_store.rb
Rails 5.2.0 RC2 throws an "uninitialized constant ActiveSupport::Digest::MD5" error. This is happening because Rails 5.2 has a new class named ActiveSupport::Digest.
=> Prefix Digest::MD5 with :: operator

lib/dalli/client.rb
In the case where a method is called on an array that returns a new array, we can mutate that new array instead of generating more intermediate arrays.
=> Reduce array allocations

lib/active_support/cache/dalli_store.rb
The only time to dup a key is if it’s the original value passed in (to prevent mutation). By adding this check I reduced object allocation by about 100 strings per page load in the app https://www.codetriage.com.
Measured using derailed benchmarks:
```
$ RAILS_SERVE_STATIC_FILES=1 RAILS_LOG_TO_STDOUT=1 DEVISE_SECRET_KEY=foo bundle exec derailed exec perf:objects
```
Before:
```
Total allocated: 1003030 bytes (8686 objects)
Total retained:  1608 bytes (13 objects)
allocated memory by gem
-----------------------------------
250490  activesupport-5.2.1
164550  dalli/lib
```
After:
```
Total allocated: 1073993 bytes (8586 objects)
Total retained:  1608 bytes (13 objects)
allocated memory by gem
-----------------------------------
250826  activesupport-5.2.1
236160  dalli/lib
```
=> Don’t dup string if it’s not the argument

lib/active_support/cache/dalli_store.rb, test/test_active_support.rb
rails 5.2 introduced Recyclable cache keys https://github.com/rails/rails/pull/29092
which means that with Rails.application.config.active_record.cache_versioning = true dalli does not work (#cache_key now returns key without version. We need to use #cache_key_with_version)
=> rails 5.2 cache_versioning support

lib/active_support/cache/dalli_store.rb, test/test_active_support.rb
`ActiveSupport::Cache::Storage` abstraction requires that `#fetch`/`#fetch_multi` methods provides a key to the block used for generating entries that does not exist in cache storage (with a given key).
I found that `ActiveSupport::Cache::DalliStore#fetch` missed this logic (in my own project).
This pull request resolves this.
now it works correctly:
```ruby
cache.fetch("a") { |key| "#{key}-calculated" } # in current implementation the key is nil
cache.fetch("a") { |key| "#{key}-calculated" } # in current pull request the key has a corresponding value
=> [BUG?] #fetch does not provide a key attribute to the fallback block (but should provide)

lib/active_support/cache/dalli_store.rb
Introduced in https://github.com/rails/rails/pull/33943 Rails will attempt to interpret if a cache store supports "cache versioning" by looking for the predicate method `supports_cache_versioning?` on the cache store class. This PR advertises support that was introduced in https://github.com/petergoldstein/dalli/pull/698.
=> Advertise support for "cache versioning"

test/test_active_support.rb
A way to reproduce #704 (not necessarily the only way).
=> Add failing test for frozen string

lib/dalli/server.rb, test/helper.rb, test/test_dalli.rb, test/test_server.rb
Rebuilt existing PR #715  on a stable master.  Also retained the error as a single line.
Thanks to @aeroastro for the original PR.
=> Log over max size as an error, rather than a warning

lib/active_support/cache/dalli_store.rb, lib/dalli/client.rb, test/test_active_support.rb, test/test_dalli.rb
- MD5 is not permitted in FIPS mode, nor is the Digest class. When operating with FIPS mode, only OpenSSL::Digest::SHAxxx is permitted.
-Closes #723
=> Added digest_class configuration option

lib/dalli/server.rb, test/test_server.rb
The problem I have stumbled upon after upgrading Rails version of my Ruby on Rails application was `dalli` marking a memcached server as failed and removing it from the list of servers for 60 seconds. In application log it looked like this:
```
Cache write: operator_name_cache/0/2 ({:expires_in=>2 days})
down_retry_delay not reached for memcached:11211 (59.990 seconds left)
DalliError: No server available
Cache write: operator_name_cache/0/17 ({:expires_in=>2 days})
down_retry_delay not reached for memcached:11211 (59.989 seconds left)
DalliError: No server available
Cache read: api_v1_results_hotel_data/453718 ({:expires_in=>3 hours})
down_retry_delay not reached for memcached:11211 (59.989 seconds left)
```
After a lot of debugging I discovered the following error in my production log: …
=> Don't treat NameError in deserialize as network error

test/helper.rb
I found these while I was browsing the code and I've noticed that they are not used anymore.
=> Remove obsolete test helpers

Appraisals
A gemfile for Rails 3 doesn't exist in `gemfiles/` so I presume that Rails 3 appraisal isn't needed anymore.
=> Remove appraisal for Rails 3

lib/active_support/cache/dalli_store.rb, lib/dalli/client.rb, test/test_active_support.rb
#724 introduced the ability to pass in a `digest_class` option. It also introduced a bug into `DalliStore` where passing a key with a length greater than 250 without passing a `digest_class` option will result in a `NoMethodError: undefined method 'hexdigest' for nil:NilClass` error. This is because there's no fallback specified for this option in DalliStore.
This PR introduces this fallback, and also makes this fallback consistent in the `Dalli::Client` class (rather than mutating the incoming options hash, it uses a fallback in the caller). It also adds a regression test for the bug.
=> DalliStore: Fix default digest_class

lib/active_support/cache/dalli_store.rb
This fixes the following warnings that are printed when using dalli with Ruby 2.7.1 (on Rails 6.0.3.1):
```
/root/project/vendor/bundle/ruby/2.7.0/gems/dalli-2.7.10/lib/active_support/cache/dalli_store.rb:420: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/root/project/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/cache/strategy/local_cache.rb:122: warning: The called method `read_entry' is defined here
```
=> Fix Ruby 2.7 keyword arguments deprecation warning

History.md, lib/dalli/client.rb, test/test_active_support.rb
This ensures that not only are servers passed as strings split on commas, but also strings nested in an array.
Currently
```ruby
ENV["MEMCACHE_SERVERS"] = "foo:11211,bar:11211"
ActiveSupport::Cache::DalliStore.new(ENV["MEMCACHE_SERVERS"]) # doesn't work
Dalli::Client.new(ENV["MEMCACHE_SERVERS"]) # works
```
This makes the latter work.
=> Handle nested comma separated servers

lib/dalli.rb
*Problem*:
It is not possible to properly instrument `ValueOverMaxSize` errors
*Reason*: 
In according to https://github.com/petergoldstein/dalli/blob/96da6efdfc3ec634583976351909e9a63bb456c2/lib/active_support/cache/dalli_store.rb#L241 Only subclasses of `DalliError` are instrumented, but `ValueOverMaxSize` is a subclass of [RuntimeError](https://github.com/petergoldstein/dalli/blob/17344b625676bd1aa45f87757e0b718a3e1ae282/lib/dalli.rb#L23)
*Solution*:
Change parent of `ValueOverMaxSize` from `RuntimeError` to `DalliError`
=> Allow instrumentation of ValueOverMaxSize

History.md, lib/dalli/client.rb, lib/dalli/server.rb, test/test_dalli.rb
Add support for "gat" (get and touch) fetch an item and simultaneously update its expiration time.
See #769
=> Add gat command support

test/benchmark_test.rb
Code as written blows up on latest rubyprof, they changed print to take an IO instead
=> Ruby-prof takes an IO object for print nowadays

README.md
This is a follow up for commit ccf55f4bf618d310072667f7049ed39fd1ceed7f
=> Corrected default values in README

lib/dalli/server.rb, test/test_server.rb
When an elasticache node is rebooted, it seems to send invalid response headers that cause dalli to think that the multiget response has completed, when there is actually still data queued up in the socket.
This causes dalli to raise `RuntimeError, "multi_response has completed"`, which is acceptable behavior. However, the problem is that the data queued up in the socket then **leaks into subsequent responses**.
It is unclear if this is an elasticache-specific bug. This may be related to the issue reported in #390.
To work around this issue, raise NetworkError and reconnect whenever we run into this state. The multiget response will be incomplete but it seems like this is being addressed in #754.
Other possible solutions:
- Call `down!` - this also works, but may cause the server to be …
=> Raise NetworkError and reconnect when multi_response_nonblock is unexpectedly called

README.md, dalli.gemspec, lib/dalli/socket.rb, scripts/install_memcached.sh, test/memcached_mock.rb, test/test_dalli.rb
Running a server with:
`memcached -Z -p 11212 -o ssl_chain_cert=./memcached.crt -o ssl_key=./memcached.key`
The client configuration is as follows:
```ruby
require 'dalli'
ssl_context = OpenSSL::SSL::SSLContext.new
ssl_context.ca_file = "./myCA.pem"
ssl_context.ssl_version = :SSLv23
ssl_context.verify_hostname = true
ssl_context.verify_mode = OpenSSL::SSL::VERIFY_PEER
d = Dalli::Client.new("memcached:11212", :ssl_context => ssl_context)
d.get("abc")
```
=> Enable SSL support

lib/dalli/client.rb, test/test_dalli.rb
This is intended to address #766
=> Restore `with` method for compatibility with existing Rails code

lib/dalli.rb, lib/dalli/client.rb, lib/dalli/key_manager.rb, test/test_dalli.rb, test/test_key_manager.rb
* Simplifies the Dalli client code a bit
* Makes it easier to do an extraction of the multi-yielder, by decoupling the multi-yielder code from the client
* Exposed and allowed resolution of issue #819 , which was a bug in the use of alternate digest classes
* Makes it simpler to support base64 encoded keys as described in the meta protocol document for a future meta implemenation
To maintain backwards compatibility the key truncation code is more complex than it could be.  Specifically, there is a difference in how clients using namespaces and clients without namespaces truncate keys.  This is essentially due to an off by one error introduced in the historical logic that didn't take into account the namespace separator character.  So without a namespace truncated keys are one character …
=> Extracts key validation and namespace handling from the Dalli client.

lib/dalli.rb, lib/dalli/client.rb, lib/dalli/servers_arg_normalizer.rb, test/test_key_manager.rb, test/test_servers_arg_normalizer.rb
The supported values for the servers arg for Dalli::Client are actually fairly complex.  For the nil case it has two fallbacks (one ENV variable, and the other a hardcoded localhost).  It supports strings which represent a single server or a comma separated set of servers.  And it supports receiving any set of those strings as an array.
On initialization the Dalli::Client immediately applies defaults as needed and normalizes this to an array of strings, wherein each string represents a single server.  This just pulls that logic out into a separate module.
=> Extract servers arg normalization

test/benchmark_test.rb
Running a get in the middle of a multi block makes handling potential error responses off the quiet requests much more difficult.  Update the test to reflect desired behavior
=> Multi blocks should not contain get commands, as those are not supported.

.rubocop_todo.yml, lib/dalli.rb, lib/dalli/client.rb, lib/dalli/protocol.rb, lib/dalli/protocol/binary.rb, lib/dalli/protocol/binary_response_processor.rb
- Reorganize binary.rb to separate response code
- Extract some minor response parsing code from incr/decr and pull into a method
- Put NOT_FOUND in top level Dalli module, preserve reference for backwards compatibility
- Rename and encapsulate @inprogress
=> Extract response processing into a separate class

lib/dalli/client.rb, lib/dalli/ring.rb, test/test_dalli.rb
This change ensure that if an error occurs in an allowed operation in a multi block (e.g. setq, replaceq, deleteq) that error response is cleared from the socket at the end of the multi block.  This ensures that subsequent operations behave as expected.  Specifically it addresses issue #772 
While this is a reasonable start, there are a couple of issues with this implementation:
1. It executes a noop operation against each server in the ring at the end of the multi block, even if no multi operation was run against that server
2. The noop operations are run in sequence, not in parallel
3. The error responses are not returned to the caller and, even if they were returned, wouldn't be usable
That all said, it accomplishes the desired effect without introducing too much of a burden. …
=> Ensure against socket corruption by errors in a multi block.

lib/dalli/client.rb, lib/dalli/key_manager.rb, lib/dalli/protocol/binary.rb, lib/dalli/ring.rb
Much of the complexity of the Dalli::Client class is in the `get_multi_yielder` code. 
The client implementation is overwhelmingly focused on the no-block version perform method - specifically taking client level calls, resolving them to the correct server, and invoking the appropriate protocol operation.   There's a small amount of additional logic for parsing arguments and initializing the Ring.
Essentially a multi-yield operation is a very different operation, and there's a lot of logic to ensure it handles errors correctly, produces expected results, etc.  Pulling that logic into a separate class, invoked by the client, will make it easier to understand and modify.
=> Prepare to Extract MultiKeyProcessor

.rubocop_todo.yml, History.md, lib/dalli.rb, lib/dalli/client.rb, lib/dalli/protocol/binary.rb, test/test_dalli.rb
This addresses issue #831 .  This can be considered a breaking change, so I'm bundling it into 3.1.0.  
This PR also includes some simplification of the get multi code.
=> Raise an error if an unsupported operation is used in a multi block

lib/dalli/pipelined_getter.rb, lib/dalli/protocol/binary.rb, lib/dalli/socket.rb, test/test_dalli.rb
This moves the PipelinedGetter closer to being a Reactor.  It also decouples the socket layer from knowledge of higher level classes (Dalli::Protocol::Binary).  This will make it much easier to extract socket/connection level concerns for reuse.
We've almost got the PipelinedGetter response processing logic suitably cleaned up that we can push process_server down into the server itself, rather than keeping it in the PipelinedGetter.
=> Removes the server attribute from Dalli socket classes, and puts server handling in the PipelinedGetter

.rubocop_todo.yml, History.md, lib/dalli.rb, lib/dalli/client.rb, lib/dalli/options.rb, lib/dalli/pipelined_getter.rb, lib/dalli/protocol/binary.rb, lib/dalli/protocol/binary/request_formatter.rb, lib/dalli/protocol/binary/response_processor.rb, lib/dalli/protocol/connection_manager.rb, lib/dalli/protocol/response_buffer.rb, lib/dalli/protocol/server_config_parser.rb, test/protocol/test_server_config_parser.rb, test/test_binary_protocol.rb, test/test_dalli.rb, test/test_quiet.rb
Once the connection logic is extracted it will become much easier to implement the meta protocol.  The goal is that after this PR, everything that's actually in the Dalli::Protocol::Binary class is related to the binary protocol specifically, and is not reusable for other protocols.  This is basically mapping Ruby commands to memcached binary requests and processing responses, and translating back to appropriate values for the Dalli::Client.
Config parameter parsing, connection handling (initialization, state management, retries), and other shared concerns should be extracted.  Binary protocol specific logic may be extracted into additional classes in the Dalli::Protocol::Binary class scope.
Once this extraction is complete, we may very well wind up inverting this a bit, where we inject …
=> Spike on extracting connection logic from Dalli::Protocol::Binary

lib/dalli/protocol/binary/response_processor.rb, lib/dalli/protocol/response_buffer.rb
- Get rid of an useless String#byteslice. `unpack1('N')` doesn't care if there's more bytes left.
- Use `String#b` to directly create a binary buffer. Saves some more encoding checks.
- Favor `byteslice` over `slice` and `#[]` as it doesn't need to check encoding as much, and allows shared strings.
For context I wanted to use [the new `unpack(offset: )` to save more allocations](https://bugs.ruby-lang.org/issues/18254), but it's not as easy with the recent refactor. I can look more into it if there's interest.
=> Minor response parsing improvements

lib/dalli/protocol/base.rb, lib/dalli/protocol/binary/response_processor.rb, lib/dalli/protocol/response_buffer.rb
The response header differs substantially between binary and meta protocol, to the level that what's in the header vs a body is really different.  It's not clear that exposing a "ResponseHeader" outside of the protocol specific package has value.  This change hides the ResponseHeader from the buffer, making it easier to make the buffer protocol agnostic.
=> Further encapsulate response header

History.md, lib/dalli/protocol/binary/response_processor.rb, test/integration/test_operations.rb
=> Fix replace so that it returns nil rather than raising an error on a miss

.github/workflows/tests.yml
Memcached 1.6.13 has been released.  Bump the version in CI.
=> Bump memcached to 1.6.13

lib/dalli/client.rb, lib/dalli/ring.rb, test/test_ring.rb
This change moves server initialization into the ring.  That's an important step for enabling properly dynamic Rings - where servers may be added or removed over time.  And by passing in the implementation class as an argument, the ring is kept generic.
=> Move server initialization into the Ring

lib/dalli/protocol/binary/sasl_authentication.rb
Aliyun returns a `null` char in the auth response which should be subbed out, otherwise PLAIN auth fails.
=> Fix: null char not replaced

lib/dalli/key_manager.rb, test/test_key_manager.rb
When creating a dalli client with a Proc for the namespace option, it
would generally mean that the namespace may change from operation to
operation. Saving the result of calling the proc in the KeyManager
instance at initialisation time means that the client will always use
the value of the namespace as it was when the client was created. If
this was the desired behaviour, it would be just as easy to pass that
value as a string instead of a Proc.
Given test/test_key_manager.rb:69 is passing a namespace_as_symbol instead of namespace_as_proc, I'm assuming this is an unintended regression from when this logic was pulled out into KeyManager
=> Evaluate Proc namespaces every time (not just at initialization)

lib/dalli/protocol/server_config_parser.rb
`URI` is used for parsing server config but is never explicitly required.
=> Require "uri" from stdlib

CHANGELOG.md, lib/dalli/protocol/meta.rb, lib/dalli/protocol/meta/request_formatter.rb, test/integration/test_network.rb, test/protocol/meta/test_request_formatter.rb, test/test_rack_session.rb
Do some input sanitization for the meta protocol.  Since this protocol uses raw test, it is possible to execute an injection attack against unsanitized inputs.
This PR explicitly sanitizes the CAS arguments and the ttl passed to flush.
I also added some missing tests for `meta_arithmetic` and fixed a few lints.
=> Fixes #932

test/helper.rb, test/integration/test_authentication.rb, test/integration/test_cas.rb, test/integration/test_compressor.rb, test/integration/test_concurrency.rb, test/integration/test_connection_pool.rb, test/integration/test_encoding.rb, test/integration/test_failover.rb, test/integration/test_marshal.rb, test/integration/test_memcached_admin.rb, test/integration/test_namespace_and_key.rb, test/integration/test_network.rb, test/integration/test_operations.rb, test/integration/test_pipelined_get.rb, test/integration/test_quiet.rb, test/integration/test_serializer.rb, test/integration/test_ttl.rb, test/protocol/meta/test_request_formatter.rb, test/protocol/test_binary.rb, test/protocol/test_server_config_parser.rb, test/protocol/test_value_compressor.rb, test/protocol/test_value_marshaller.rb, test/protocol/test_value_serializer.rb, test/test_client_options.rb, test/test_key_manager.rb, test/test_rack_session.rb, test/test_ring.rb, test/test_servers_arg_normalizer.rb
This includes several spacing changes to satisfy the latest Rubocop::Minitest.
There is also a [bug in the latest version](https://github.com/rubocop/rubocop-minitest/issues/187) that is causing errors in the Rubocop run.  So my expectation is that this doesn't run green, but will be fixed once that bug is resolved.
=> Changes for new empty line before assert cop.

lib/dalli/socket.rb
Since we know exactly how many bytes we expect, instead of stating with an empty string and resizing many times, we can directly ask Ruby to preallocate the necessary space.
For large responses this saves many reallocations and copies.
=> Preallocate the read buffer in Socket#readfull

lib/dalli/protocol/binary/response_processor.rb, lib/dalli/protocol/meta/key_regularizer.rb, test/test_compressor.rb
This doesn't really matter much in the grand scheme of things but is a pet peeve of mine. It's very marginally faster as Ruby doesn't have to search for that name in the encoding table.
=> Pass Encoding instances rather than encoding names as String

lib/dalli/pid_cache.rb, lib/dalli/protocol/connection_manager.rb
Ref: https://bugs.ruby-lang.org/issues/19443
Recent `glibc` no longer cache the PID, so every call to `Process.pid` end up emitting a syscall which as an impact on performance.
Ruby 3.3 may or may not do PID caching, in the meantime we can implement our own caching in Ruby 3.1+ using the `Process._fork` callback.
NB: This is very much the same code I'm about to merge in redis-client: https://github.com/redis-rb/redis-client/pull/91, and probably Active Record too https://github.com/rails/rails/pull/47419
FYI @dalehamel
=> Cache Process.pid on Ruby 3.1+

CHANGELOG.md, lib/dalli/protocol/base.rb, lib/dalli/protocol/connection_manager.rb, test/integration/test_network.rb, test/integration/test_pipelined_get.rb
Fix: https://github.com/petergoldstein/dalli/issues/956
While it's heavily discouraged, `Timeout.timeout` end up being relatively frequently used in production, so ideally it's better to try to handle it gracefully.
This patch is inspired from https://github.com/redis-rb/redis-client/commit/5f82254583c75b1f914590ae6a3e159ed07c0ac9 before sending a request we increment a counter, and once we fully read the response(s), we decrement it.
If the counter is not 0 when we start a request, we know the connection may have unread responses from a previously aborted request, and we automatically discard it.
=> Better handle Thread#raise and Thread#kill

README.md
The old link now 404, this commit updates the URI to the new URI.
This is a rebased version of #970.  Thanks @JuanitoFatas !
=> Fix rubydoc info URI points to Client API

CHANGELOG.md, lib/dalli/protocol.rb, lib/dalli/protocol/base.rb, lib/dalli/protocol/connection_manager.rb
One scenario in which this happens is when a firewall silently drops connections between clients and memcached instances.
With this patch the client reopens the connection and the request succeeds. Without it, IO:TimeoutError is raised for the application to handle which deviates from Dalli behavior under Ruby 3.1 and earlier.
Addresses #967 and fixes the remaining lint in #968
=> rescue IO::TimeoutError raised by Ruby since 3.2.0 on blocking reads/writes

lib/dalli/socket.rb
* Use Socket's connect_timeout (available since Ruby 3.0) instead of Timeout when possible
* Pass socket_timeout down to the socket's send and recieve timeouts.
=> Better socket_timeout handling

dalli.gemspec
base64 is loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0.
Adding `base64` to gemspec to avoid this warning in Ruby 3.3 and allow Dalli to run against ruby-head
Close #981
=> Add base64 to gemspec

lib/dalli/pipelined_getter.rb, test/integration/test_network.rb
Fixes https://github.com/petergoldstein/dalli/issues/966.
If sending the pipelined get commands fails with a network error, the socket will be closed when we try to send the no-op command. `alive?` reconnects if possible, but we only need to send the no-op if the get commands were successfully sent.
Before https://github.com/petergoldstein/dalli/pull/963, reconnecting to send a no-op was harmless, but now that pipelined requests are tracked in their entirety, an error is raised since there is no request in progress.
=> Don't reconnect to send pipelined request no-op

dalli.gemspec, lib/dalli/protocol/meta/key_regularizer.rb
#982 added `base64` as a dependency in order to avoid a warning with Ruby 3.3
The `base64` gem is mostly a wrapper around `pack`/`unpack` and as such is easy to replace. Other gems have opted for the same approach:
* https://github.com/rack/rack/pull/2110
* https://github.com/lostisland/faraday/pull/1541
* https://github.com/rubocop/rubocop/pull/12313
* https://github.com/sidekiq/sidekiq/pull/6151
* etc
=> Drop dependency on base64

dalli.gemspec
This PR adds [`bug_tracker_uri` and `changelog_uri`](https://guides.rubygems.org/specification-reference/#metadata) for [rubygems.org](https://rubygems.org/gems/dalli)
=> Add metadata for rubygems.org

lib/dalli/socket.rb
Closes #987
In version 3.2.7 socket_timeout option was introduced for TCPSocket.
This works unless `resolv-replace` gem is loaded (which was added to ruby standard library since version 3.0.0).
This commit adds another check besides the ruby version check to avoid breaking dalli for applications that have `resolv-replace` gem required.
=> Fix conflict with resolv-replace gem

CHANGELOG.md, lib/dalli/protocol/connection_manager.rb, test/integration/test_network.rb
Since https://github.com/petergoldstein/dalli/pull/977, `Dalli::Socket::TCP.open` can also raise this error.
=> Handle IO::TimeoutError when establishing connection

lib/dalli/protocol/ttl_sanitizer.rb
🤓 
Current output:
```
Expiration interval (6569244) too long for Memcached and too short to be a future timestamp,converting to an expiration timestamp
```
With this fix:
```
Expiration interval (6569244) too long for Memcached and too short to be a future timestamp, converting to an expiration timestamp
```
=> Add a space to properly format multi-line log output

dalli.gemspec, test/helper.rb, test/integration/test_network.rb, test/protocol/test_binary.rb
This PR avoids a Ruby warning.
There was a warning in ruby-head (3.4) that in Ruby 3.5 `logger` and `ostruct` will not be built-in gems, but regular gems.
```
/home/runner/work/dalli/dalli/test/helper.rb:13: warning: logger was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.5.0. Add logger to your Gemfile or gemspec.
/home/runner/work/dalli/dalli/test/helper.rb:14: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.5.0. Add ostruct to your Gemfile or gemspec.
```
This change avoids that warning.
---
In addition, the `ostruct` dependency wasn't in actual use, just `require 'ostruct'` statements. It was possible to fully omit that and pass all tests.
A second commit with a linting …
=> Add logger as a dependency, drop ostruct for tests

CHANGELOG.md, lib/dalli/protocol/meta/response_processor.rb, test/integration/test_operations.rb
if meta protocol `get` response data included terminator `\r\n` then occur error
```
1) Error:
operations::using the meta protocol::get#test_0002_return the value that include TERMINATOR on a hit:
Dalli::UnmarshalError: Unable to unmarshal value: marshal data too short
lib/dalli/protocol/value_serializer.rb:65:in `filter_argument_error'
lib/dalli/protocol/value_serializer.rb:51:in `rescue in retrieve'
lib/dalli/protocol/value_serializer.rb:45:in `retrieve'
lib/dalli/protocol/value_marshaller.rb:44:in `retrieve'
lib/dalli/protocol/meta/response_processor.rb:35:in `meta_get_with_value'
lib/dalli/protocol/meta.rb:30:in `get'
lib/dalli/protocol/base.rb:36:in `request'
lib/dalli/options.rb:18:in `block in request'
lib/dalli/options.rb:17:in `synchronize'
lib/dalli/options.rb:17:in `request' …
```
=> Fix cannot read response data included terminator when use meta protocol

lib/dalli/protocol/connection_manager.rb
The `detail` variable was created twice, it seems to have been an artifact of a previous refactor
=> connection_manager: remove unnecessary variable

CHANGELOG.md, Gemfile, lib/dalli.rb, lib/dalli/protocol/meta/response_processor.rb, test/integration/test_network.rb
As per the Memcached spec, SERVER_ERROR is a valid value to return, alongside the error message. This only seems to be valid for the Meta/Text protocols.
I have added support so things like Envoy that return SERVER_ERROR will be handled correctly and raised as an appropriate error.
I also added the `debug` gem to `:development` and `:test` since it is very useful to be able to add things like breakpoints while debugging.
=> Handle SERVER_ERROR from Memcached

lib/dalli/socket.rb, test/integration/test_network.rb
Currently we're relying on the `SO_SNDTIMEO` and `SO_RCVTIMEO` socket options for connect/read/write timeouts. [As of CRuby 3.0, sockets are non-blocking by default](https://github.com/ruby/ruby/blame/78f188524f551c97b1a7a44ae13514729f1a21c7/ext/socket/init.c#L411-L434) which means that these socket options do not have any effect by default:
>Timeouts only have effect for system calls that perform socket I/O (e.g., [accept(2)](https://man7.org/linux/man-pages/man2/accept.2.html), [connect(2)](https://man7.org/linux/man-pages/man2/connect.2.html), [read(2)](https://man7.org/linux/man-pages/man2/read.2.html), [recvmsg(2)](https://man7.org/linux/man-pages/man2/recvmsg.2.html), [send(2)](https://man7.org/linux/man-pages/man2/send.2.html), …
=> feat: I/O Timeout

.github/workflows/benchmarks.yml, .github/workflows/profile.yml, bin/benchmark, bin/profile
This will make it easier for us to start upstreaming some of the performance and latency related PRs we have been testing out. We should be able to compare profiles before and after applying change and post any benchmark differences as well...
current benchmark:
```
❯❯❯$ bundle exec bin/benchmark                                                                                        <bundler> [main]
yjit: false
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]
Warming up --------------------------------------
client set   691.000 i/100ms
raw sock set     1.403k i/100ms
Calculating -------------------------------------
client set      6.391k (± 9.7%) i/s -     63.572k in  10.035280s
raw sock set     14.013k (± 2.0%) i/s -    140.300k in  10.016703s
Comparison:
raw sock set: …
```
=> add a benchmark and profile script and hook into CI

.github/workflows/benchmarks.yml, .github/workflows/profile.yml, bin/benchmark, bin/profile, lib/dalli/protocol/meta.rb, lib/dalli/protocol/meta/request_formatter.rb, test/protocol/meta/test_request_formatter.rb
Ok, with the benchmark and profile we can start to pull over some performance improvements. I updated the benchmark and profile to support the meta protocol client as well as the binary. We haven't been working on the binary, but it is good to have both as we don't want to accidentally cause any regressions with the binary protocol support before we deprecate it.
> using vernier profiler on the set command we can see it is spending a lot of time with string manipulation, this can be especially bad with very large values.
The before benchmark, shows that meta set is the slowest 
```
❯❯❯$ BENCH_TARGET=set RUBY_YJIT_ENABLE=1 bundle exec bin/benchmark                                                 <bundler> [main 
yjit: true
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) +YJIT [arm64-darwin23] …
```
=> update benchmark & profile to support meta client and commit performance fix for meta protocol

.github/workflows/tests.yml, scripts/install_memcached.sh, scripts/memcached_1.5.22.patch
Avoids brownouts on deprecated ubuntu-20 and matches everything else.
In order to compile memcached 1.5 (last released in 2020) on a recent ubuntu I had to manually patch some compiler errors
=> Use ubuntu-latest for tests

CHANGELOG.md, lib/rack/session/dalli.rb, test/test_rack_session.rb
It fixes the session recovery after deletion, the same security advisories were published recently within `rack` repos:
* [rack](https://github.com/rack/rack/security/advisories/GHSA-vpfw-47h7-xj4g)
* [rack-session](https://github.com/rack/rack-session/security/advisories/GHSA-9j94-67jr-4cqj)
[Rack session middleware](https://github.com/rack/rack/blob/v2.2.13/lib/rack/session/abstract/id.rb#L263-L270) prepares the session at the beginning of request, then saves is back to the store with possible changes applied by host rack application. This way the session becomes to be a subject of race conditions in general sense over concurrent rack requests.
In particular the following scenario is possible:
1. Given that user is logged in involving warden gem (devise-backed app);
2. Frontend runs …
=> Fix session recovery after deletion

lib/dalli/protocol/value_serializer.rb, test/integration/test_serializer.rb
Going through `Marshal.load/dump` (or other serializers) when the value is already a string is quite costly for not a whole lot of value.
The only real benefit is that it automatically preserve the string encoding, but we can assume the overwhelming majority of strings are either UTF-8 or BINARY, so we can encode that in the bitflags.
For strings that have a different encoding, or objects that inherit from `String` we can continue to use the serializer.
Note that only the `#store` path checks for the option. `#retrieve` always handle this new format. This is so that you can seemlessly upgrade without having to flush your caches. You can first upgrade dalli and then later turn on the option.
It would be nice to make this option a default at some point though.
@danmayer @nickamorim (Ref: …
=> Add `string_fastpath` option to save on serializing simple strings

.devcontainer/Dockerfile, .devcontainer/README.md, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .devcontainer/setup.sh
When I was working on #1036 I needed a clean environment to work from. Since a lot of people use VS Code these days, I setup a devcontainer. I figured I'd share to save others time.
This borrows from the setup that is done in the GHA for running the tests. It should let a contributor get up and running pretty quickly and easily regardless of what system they are developing on.
=> Create a devcontainer setup

CHANGELOG.md, lib/dalli/protocol/connection_manager.rb, test/integration/test_fork_safety.rb, test/protocol/test_connection_manager.rb, test/test_fork_safety.rb
Today, when a Dalli connection is active and a forked child process attempts to use it, the connection is closed and an exception is raised. When this happens in a forking app server environment, it can cause the spawned process to fall into a crash back loop, fail to start, etc. In the event the process fully loads, the first request it serves up that hits the cache will crash as well.
Historically, people were encouraged to manually close connections when forking to avoid this. This is not always feasible without monkey patching and hacks though, like in the case where Dalli is used by Rails in the [ActiveSupport::Cache::MemCacheStore](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/cache/mem_cache_store.rb)
This change aims to make Dalli play nicer in forking …
=> Reconnect when a fork is detected
