lib/dalli/socket.rb

@petergoldstein I want your opinion on this before merge ;-)

Solve issue #523 - UNIX sockets on windows platform

---

lib/dalli/server.rb

Fixes #440.
Since #208 "Dalli no longer needs to be reset after Unicorn/Passenger fork," which implies that this situation will be transparently handled by the library without logging any errors, without any workarounds required. However, the confusion started with #368 when an `info` log message was added that implied that this situation was not permitted and was causing a `RuntimeError` on the server.
Since sharing a socket with client processes is now handled perfectly fine by the library, this PR changes the log message caused by this socket-sharing condition from a scary:
```
my-test-server:11211 failed (count: 0) RuntimeError: Cannot share client between multiple processes
```
to a more reasonable:
```
Fork detected, re-connecting child process...
```
It also skips incrementing the …

Do not treat socket sharing as a failure

---

History.md
README.md
lib/active_support/cache/dalli_store.rb
lib/dalli/client.rb
lib/dalli/server.rb
test/helper.rb
test/memcached_mock.rb
test/test_active_support.rb
test/test_dalli.rb

support the fetch operation with nil values

---

test/helper.rb
test/test_active_support.rb

@mperham @petergoldstein 
I was trying to work on the dalli store vs memcached store issue but this clutter / weirdness git me irritated ... good to merge ?
best viewed [without whitespace](https://github.com/mperham/dalli/pull/566/files?w=1)

dry up cache creation methods

---

Rakefile
test/benchmark_test.rb
test/test_cas_client.rb
test/test_compressor.rb
test/test_dalli.rb
test/test_encoding.rb
test/test_failover.rb
test/test_network.rb
test/test_rack_session.rb
test/test_ring.rb
test/test_sasl.rb
test/test_serializer.rb
test/test_server.rb

make all tests run without adding -I test

---

test/test_active_support.rb

@mperham @petergoldstein
atm test output has a lot of errors, that we expect to be there, but it's pretty distracting and can be confusing to new contributors
```
................E, [2015-11-13T15:24:00.651430 #12658] ERROR -- : DalliError: No server available
E, [2015-11-13T15:24:00.777870 #12658] ERROR -- : DalliError: No server available
E, [2015-11-13T15:24:00.778928 #12658] ERROR -- : DalliError: No server available
E, [2015-11-13T15:24:00.779397 #12658] ERROR -- : DalliError: No server available
E, [2015-11-13T15:24:00.779660 #12658] ERROR -- : DalliError: No server available
E, [2015-11-13T15:24:00.779914 #12658] ERROR -- : DalliError: No server available
E, [2015-11-13T15:24:00.780176 #12658] ERROR -- : DalliError: No server available
E, [2015-11-13T15:24:00.780409 #12658] ERROR …
```

silence test errors

---

Gemfile
Rakefile
dalli.gemspec
test/helper.rb

use bundler and stop rescuing LoadError

---

test/test_active_support.rb

@mperham @petergoldstein
a preview of what I have in mind to tighten local cache testing, looks good ? -> I'll convert more tests and kick out the standalone LocaleCache tests
decided against using something that is inside the testcase so that you can dig into a specific issue with `ruby xxx_test.rb -n 'bla bla with LocaleCache'`

test with and without local cache

---

lib/dalli/server.rb

https://bugs.ruby-lang.org/issues/11398

TimeoutError is deprecated

---

lib/action_dispatch/middleware/session/dalli_store.rb
lib/active_support/cache/dalli_store.rb
lib/dalli.rb
lib/dalli/cas/client.rb
lib/dalli/client.rb
lib/dalli/compressor.rb
lib/dalli/options.rb
lib/dalli/railtie.rb
lib/dalli/ring.rb
lib/dalli/server.rb
lib/dalli/socket.rb
lib/dalli/version.rb
lib/rack/session/dalli.rb
test/benchmark_test.rb
test/helper.rb
test/memcached_mock.rb
test/test_active_support.rb
test/test_cas_client.rb
test/test_compressor.rb
test/test_dalli.rb
test/test_encoding.rb
test/test_failover.rb
test/test_network.rb
test/test_rack_session.rb
test/test_ring.rb
test/test_sasl.rb
test/test_serializer.rb
test/test_server.rb

Changes for frozen string literal compatibility

---

README.md

Hi.  I've updated some documentation to include references to setting the server port and weight.

Add details of port and weight configuration to documentation.

---

lib/dalli/server.rb

Assigned but unused variable - type

---

.travis.yml
gemfiles/rails5.gemfile

Combine @tiarly 's Memcached SASL fix with addition of Ruby 2.5.x, upgrade of existing Rubies, and Minitest/Rails fix.

Get specs running again

---

lib/active_support/cache/dalli_store.rb
test/test_active_support.rb

Support large cache keys on fetch multi

---

lib/active_support/cache/dalli_store.rb

Reverts petergoldstein/dalli#694

Revert "Don’t dup string if it’s not the argument"

---

test/memcached_mock.rb

Thanks to @deepj for the original patch.  Opening a PR on a stable master.

Better detection of fork support

---

.rubocop_todo.yml
lib/dalli.rb
lib/dalli/protocol/binary.rb
lib/dalli/protocol/binary/response_processor.rb
lib/dalli/protocol/binary/sasl_authentication.rb
lib/dalli/version.rb
test/utils/memcached_manager.rb

- Unify memcached version references
- Extract SASL processing into a dedicated module
- Extract/rename some methods
- Remove some unneeded constants
- Update noop response processing to be resilient against intermediate errors

Assorted cleanup and refactoring

---

History.md
lib/dalli/protocol/binary.rb
lib/dalli/protocol/binary/response_processor.rb
test/test_cas_client.rb
test/test_dalli.rb

Return a falsey value rather than raise an error on nonexist key for deletes

---

History.md
lib/dalli/client.rb
test/integration/test_cas.rb

* Eliminate special case for 'Not found' value
* Add tests to ensure we're handling consistently

Fix handling of 'Not found' value in cas/cas!

---

README.md

Fixes #911 - Update to a working link

Fixes #911 - Link in README is broken

---

lib/rack/session/dalli.rb

Right now older Dalli sessions references are causing code level errors because these sessions don't respond to private_id.  This change explicitly checks whether the sid responds to private_id before calling.  And it makes the callers handle a nil return value (when the sid doesn't respond to private_id)
This is an alternate to #917

Avoid errors on old Dalli sessions

---

.github/workflows/tests.yml

Also bumped memcached 16.x to latest minor.

Test with Ubuntu 20.04 to support build of memcached 15.x

---

CHANGELOG.md

This PR adds a CHANGELOG line for #1011.

CHANGELOG.md: Add #1011 to changelog
